FPS = 6
BRIGHTNESS_FACTOR = 0.5
SPEED_FACTOR = 1.15
OUTPUT_VIDEO_FORMAT = "mp4"


TITLE_FONTSIZE = 42
TITLE_MAX_CHARS_PER_LINE = 32
TITLE_FONT = 'Arial-Bold'
TITLE_COLOR = "#FAFAFA"
TITLE_STROKE_COLOR = "#FFFFFF"
TITLE_BG_COLOR = "#00000080"
TITLE_METHOD = 'label'
TITLE_POSITION = ('center', 0.8)
TITLE_STROKE_WIDTH = 0.95
# TITLE_SIZE = (1028, None)  # Video size for caption method

# CHUNK_SIZE = 8
CHUNK_DURATION = 2 # seconds each chunk will appear
SUBTITLE_FONTSIZE = 60
SUBTITLE_MAX_CHARS_PER_LINE = 35
SUBTITLE_FONT = 'Arial'
SUBTITLE_COLOR = '#eda3ff' # blue
SUBTITLE_STROKE_COLOR = "#FAFAFA" # white 
SUBTITLE_BG_COLOR = "#00000080"
SUBTITLE_METHOD = 'label'
SUBTITLE_POSITION = ('center',0.4)
SUBTITLE_STROKE_WIDTH = 0.8



# ----------------------- BELOW ARE THE THUMBNAIL CONFIGS ----------------------------
BG_BRIGHTNESS_FACTOR = 0.5
THUMBNAIL_CLIP_DURATION = 2
OUTPUT_THUMBNAIL_FORMAT = "png"

THUMBNAIL_TITLE_FONTSIZE = 62
THUMBNAIL_TITLE_MAX_CHARS_PER_LINE = 20
THUMBNAIL_TITLE_FONT = 'Arial-Bold'
THUMBNAIL_TITLE_COLOR = "#FAFAFA"
THUMBNAIL_TITLE_STROKE_COLOR = "#FFFFFF"
THUMBNAIL_TITLE_BG_COLOR = "#00000080"
THUMBNAIL_TITLE_METHOD = 'label'
THUMBNAIL_TITLE_POSITION = ('center', 0.5)
THUMBNAIL_TITLE_STROKE_WIDTH = 0.95
