FPS = 24
BRIGHTNESS_FACTOR = 0.5
SPEED_FACTOR = 1.2
OUTPUT_VIDEO_FILENAME = "output_video.mp4"


TITLE_FONTSIZE = 42
TITLE_MAX_CHARS_PER_LINE = 32
TITLE_FONT = 'Arial-Bold'
TITLE_COLOR = "#FAFAFA"
TITLE_STROKE_COLOR = "#FFFFFF"
TITLE_BG_COLOR = "#00000080"
TITLE_METHOD = 'label'
TITLE_POSITION = ('center', 0.8)
TITLE_STROKE_WIDTH = 0.95
# TITLE_SIZE = (1028, None)  # Video size for caption method

# CHUNK_SIZE = 8
CHUNK_DURATION = 2 # seconds each chunk will appear
SUBTITLE_FONTSIZE = 60
SUBTITLE_MAX_CHARS_PER_LINE = 40
SUBTITLE_FONT = 'Arial'
SUBTITLE_COLOR = '#eda3ff' # blue
SUBTITLE_STROKE_COLOR = "#FAFAFA" # white 
SUBTITLE_BG_COLOR = "#00000080"
SUBTITLE_METHOD = 'label'
SUBTITLE_POSITION = ('center',0.4)
SUBTITLE_STROKE_WIDTH = 0.8